### ISSUE TITLE
Cannot reproduce the reuslts of alphaQE+RRT

### ISSUE THREAD

**Issue by yuyouxixi** [uvavision/RerankingTransformer#7]
Hello, i tried to reproduce your results shown in the iccv paper, while cannot get the consistent results. 
![image](https://user-images.githubusercontent.com/41193400/155286086-ca6ee7af-8f51-4047-b8e1-bd87274aa373.png)
I have checked all the hyperparameters to ensure them to be consistent with those in the paper. Do you have any idea with this?

**Comment by fwtan** [comment]
Thank you for pointing this out! I confirm that there is an error in Table 3 of our paper: the numbers for QE+RRT were obtained by reranking the top-200, instead of top-100 of the images. These can be verified by changing [this line of code](https://github.com/uvavision/RerankingTransformer/blob/f5b99d68efe363327a4ea3e8db11c97da6a6146a/RRT_GLD/utils/metrics.py#L73). I'm sorry for this mistake. The results do not change the observation made in the paper: combining QE and RRT outperforms QE-only and RRT-only. I will submit a revised version of the paper to arxiv.
